name: CI-CD

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Running unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 16.20.2
              uses: actions/setup-node@v4
              with:
                node-version: '16.20.2'

            - name: Install dependencies
              run: npm i

            - name: Run unit tests
              run: npm run test